//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlapWarehouseApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public int Id { get; protected set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public int ElementId { get; protected set; }
    
        public virtual Element Element { get; set; }
    }
}
