//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlapWarehouseApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cube
    {
        public Cube()
        {
            this.Dimensions = new HashSet<Dimension>();
            this.Facts = new HashSet<Fact>();
        }
    
        public int Id { get; protected set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ServerId { get; protected set; }
    
        public virtual Server Server { get; set; }
        public virtual ICollection<Dimension> Dimensions { get; set; }
        public virtual ICollection<Fact> Facts { get; set; }
    }
}
