//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlapWarehouseApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        public Element()
        {
            this.Children = new HashSet<Element>();
            this.Attributes = new HashSet<Attribute>();
        }
    
        public int Id { get; protected set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Caption { get; set; }
        public Nullable<float> Weight { get; set; }
        public Nullable<short> Order { get; set; }
        public int DimensionId { get; protected set; }
        public Nullable<int> ElementId { get; protected set; }
    
        public virtual Dimension Dimension { get; set; }
        public virtual Element Parent { get; set; }
        public virtual ICollection<Element> Children { get; set; }
        public virtual ICollection<Attribute> Attributes { get; set; }
    }
}
