//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlapWarehouseApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fact
    {
        public int Id { get; set; }
        public int CubeId { get; set; }
        public string ElementId1 { get; set; }
        public string ElementId2 { get; set; }
        public string ElementId3 { get; set; }
        public string ElementId4 { get; set; }
        public string ElementId5 { get; set; }
        public double Value { get; set; }
    
        public virtual Cube Cube { get; set; }
    }
}
